---
- name: Configuration des VMs pour K3s et PostgreSQL HA
  hosts: all
  become: true

  tasks:
    - name: Installer les paquets requis
      dnf:
        name: [socat, firewalld, iptables-services, postgresql-server]
        state: present

    - name: Démarrer Firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes

- name: Installer et configurer K3s sur le master
  hosts: k3s_master
  become: true
  tasks:
    - name: Installer K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -

    - name: Copier kubeconfig localement
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3s.yaml
        flat: yes

- name: Joindre les nœuds K3s
  hosts: k3s_nodes
  become: true
  tasks:
    - name: Récupérer le token du cluster
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      delegate_to: k3s_master

    - name: Joindre le cluster K3s
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://10.0.0.9:6443" K3S_TOKEN="{{ k3s_token.stdout }}" sh -

- name: Configurer le proxy pour K3s
  hosts: k3s_proxy
  become: true
  tasks:
    - name: Activer le port 6443
      firewalld:
        port: 6443/tcp
        permanent: yes
        state: enabled

    - name: Configurer socat pour rediriger les requêtes vers le master
      command: sudo socat TCP-LISTEN:6443,fork TCP:10.0.0.9:6443

- name: Déploiement PostgreSQL HA sur K3s
  hosts: k3s_master
  become: true
  tasks:
    - name: Appliquer les manifests PostgreSQL HA
      shell: kubectl apply -f manifests/postgres-ha.yaml
