name: Deploy Infrastructure & Configure VMs

on:
  push:
    branches:
      - CI/CD-P51

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Reset Terraform cache
        run: rm -rf .terraform
        working-directory: Terraform
        
      - name: Tester connexion SSH et API K3s
        run: |
          nc -zv $(terraform output -raw k3s_master_internal_ip) 22 || echo "SSH Bloqué"
          nc -zv $(terraform output -raw k3s_proxy_public_ip) 6443 || echo "API K3s Bloquée"
        working-directory: Terraform



      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var="gcp_credentials=${{ secrets.GCP_CREDENTIALS }}" -var="gcp_project=${{ secrets.GCP_PROJECT }}"
        working-directory: Terraform


  configure-vms:
    needs: terraform-apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Installer Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Lancer la configuration Ansible
        run: ansible-playbook -i ansible/inventory.ini ansible/setup.yml
