name: Déploiment Ansible sur Google Cloud

on:
  push:
    branches:
      - CI/CD-P51
  workflow_dispatch:

jobs:
  ansible-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install Google Cloud CLI
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      - name: Activate Service Account
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
          gcloud auth activate-service-account ansible@refined-gravity-448109.iam.gserviceaccount.com --key-file=gcp-key.json
          gcloud config set project refined-gravity-448109-m7

      - name: SSH into VM and Update System
        run: |
          gcloud compute ssh k3s-master --zone europe-west1-b --command "sudo dnf update -y" --quiet
