name: Setup Ansible on GCP

on:
  push:
    branches:
      - CI/CD-P51
  workflow_dispatch:

jobs:
  ansible-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup gcloud CLI
        run: |
          sudo apt-get install -y google-cloud-sdk
          gcloud auth activate-service-account --key-file <(echo "$GCP_SERVICE_ACCOUNT_KEY")
          gcloud config set project refined-gravity-448109-m7

      - name: SSH into VM and Update System
        run: |
          gcloud compute ssh ansible --zone europe-west1-b --command "sudo dnf update -y" --quiet
